CREATE TABLE IF NOT EXISTS < GLOBAL_DB_NAME >.res_queue (
    work_id INT AUTO_INCREMENT PRIMARY KEY,
    res_name VARCHAR(255) NOT NULL,
    status ENUM('new', 'in_progress', 'done', 'error') DEFAULT 'new',
    res_url VARCHAR(500),
    created_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP,
    updated_at TIMESTAMP DEFAULT CURRENT_TIMESTAMP ON UPDATE CURRENT_TIMESTAMP
);